server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: user-menu
          uri: lb://USER-MENU
          predicates:
            - Path=/menu/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/